### PR TITLE
fix: update source code preview in storybook

### PR DESCRIPTION
**Pull request by harshdoesdev**
We have created a web component and action which updates the source code in the `Source` panel. This does not work with `fastn serve` ([this](https://github.com/fastn-stack/fastn/pull/1833) fixes this issue). You will need to build the project and then serve the build output using a static file server, for example: `python -m http.server`.

@MeenuKumari28

### CODE REVIEW

**Comment by amitu** [comment]
> This command does not work with `fastn serve`.

@harshdoesdev, any idea why?

**Comment by harshdoesdev** [comment]
> > This command does not work with `fastn serve`.
> 
> @harshdoesdev, any idea why?

Because `fastn serve` does not allows access to raw `.ftd` files and fails with error: `we do not serve ftd file source`

**Comment by amitu** [comment]
Can you add an env variable, which when set fastn serves ftd files?

**Comment by harshdoesdev** [comment]
> Can you add an env variable, which when set fastn serves ftd files?

PR: https://github.com/fastn-stack/fastn/pull/1833

**Review by amitu — APPROVED** [review]

**Pull request merged**
