### PR TITLE
featured template

### PR DESCRIPTION
**Pull request by MeenuKumari28**
I have added all the ready-to-use templates. I have also created a user interface for featured templates in /featured/ path and added a `Use Template` button on hover.

Capture

### CODE REVIEW

**Comment by amitu** [comment]
Don't embed iFrame, scrollbars look ugly. Use images.

**Comment by siddhantk232** [comment]
> Don't embed iFrame, scrollbars look ugly. Use images.

We don't have a preview image for a website. We could render the website and take a snapshot (as png) and save that somewhere but that comes with its own complications:

- The website preview won't look good in a thumbnail size image
- Too much resource usage

@MeenuKumari28 Let's remove the image and just use text. Have two buttons "Use" and "Preview" along with the title. Maybe use [this icon](https://phosphoricons.com/?q=%22external%22) with the Preview button and have it open the website `preview-url` in a new tab. Not the best UI but this will do for now.

cc: @amitu

**Comment by amitu** [comment]
> We don't have a preview image for a website.

What do you mean by this? We can take screenshots, and use them. 

Do not remove images, they def help, as names are not meaningful when you are selecting design.

**Comment by siddhantk232** [comment]
> > We don't have a preview image for a website.
> 
> What do you mean by this? We can take screenshots, and use them.
> 
> Do not remove images, they def help, as names are not meaningful when you are selecting design.

I initially planned to list every website that has their source public to be listed on this page (bad idea ik). This is why I was confused on how to get images for all of them.

Hardcoding selected templates on this page is certainly a better idea and, we can use screenshots too which is awesome!

**Comment by MeenuKumari28** [comment]
> @MeenuKumari28 your resume template should also appear on this page.

Yes, but that is not mobile-optimized yet. Should I add it? @siddhantk232

**Comment by siddhantk232** [comment]
> > @MeenuKumari28 your resume template should also appear on this page.
> 
> Yes, but that is not mobile-optimized yet. Should I add it? @siddhantk232

Yes. You can update the template after you've added it on this page. Those who'll use this template in future will get the updated mobile optimized version

**Comment by amitu** [comment]
> I initially planned to list every website that has their source public to be listed on this page (bad idea ik). This is why I was confused on how to get images for all of them.

Makes sense. Even otherwise maintaining the screenshots manually is going to be tedious and error prone. We have to automate that someday. Maybe an explicit publish step should be needed for all template, and any change done since last publish will not be visible to users. The publish action can be load the site in frame and take screenshots using browser APIs and upload somewhere.

**Comment by MeenuKumari28** [comment]
> > Don't embed iFrame, scrollbars look ugly. Use images.
> 
> Used image instead of iframe. ft @amitu @siddhantk232

Capture
Updated design suggested  by @siddhantk232

**Comment by siddhantk232** [comment]
LGTM

**Review by siddhantk232 — APPROVED** [review]

**Pull request merged**
