### PR TITLE
Added help_requested, public_history and public_source to site setting page

### PR DESCRIPTION
**Pull request by Arpita-Jaiswal**
Checkout https://github.com/FifthTry/dotcom/pull/154/ for more detail

# Help Requested Disabled

## Public Source and Public History
127 0 0 1_bb_setting_

## Private Source and Public History
127 0 0 1_bb_setting_ (1)

## Private Source and Private History
127 0 0 1_bb_setting_ (2)

## Public Source and Private History
127 0 0 1_bb_setting_ (2)

# Help Requested Enabled

127 0 0 1_bb_setting_ (4)

### CODE REVIEW

**Comment by amitu** [comment]
I prefer the headings "History is private", "History is visible to the world". Similarly for source. 

Also show History settings only if Source is public (source private, history public feels nonsense to me, so we should not allow it).

Also on backend, you can make history is private if source is changed to private in db, but I prefer you leave the users last setting for history as is, and when checking I should show history do an and on the two. This way if user changes from source public history public to source private and then back to source public they land on source public history public. If you change history to private when source becomes private (this is safe), you can not automatically make history public when source becomes public to user will end in source public history public in the scenario I described, and user will have to take one more action (which they can forget to do).

**Comment by amitu** [comment]
Also "Make Source Public" is better than "Enable Source Public", etc.

**Comment by Arpita-Jaiswal** [comment]
@amitu Please review again.

**Comment by amitu** [comment]
I have asked for this:

> Also show History settings only if Source is public (source private, history public feels nonsense to me, so we should not allow it).

But I still see this: Private Source and Public History.

**Comment by amitu** [comment]
On a second thought, this is not what I had in mind, but we can go ahead with it. I somehow still prefer not showing the history section altogether is better, but I also see merit in what you have done. 

Since its not clear what I am asking is better, what you have done should go live as "makers gets to decide".

**Review by amitu — APPROVED** [review]

**Pull request merged**
