### PR TITLE
fixed pages responsiveness

### PR DESCRIPTION
**Pull request by MeenuKumari28**
fixed pages responsiveness

### CODE REVIEW

**Comment by amitu** [comment]
@MeenuKumari28 this is how it looks in my browser. Try resizing the browser a bit, and scroll down.

image

**Comment by amitu** [comment]
@MeenuKumari28 also notice that the dark mode switch is over the Powered by fastn button. Also the Powered by fastn is not a button at all, it should link to fastn.com.

**Comment by MeenuKumari28** [comment]
> @MeenuKumari28 this is how it looks in my browser. Try resizing the browser a bit, and scroll down.
> 
> image

@amitu Once you refresh the page it will get fixed.

**Comment by amitu** [comment]
> @amitu Once you refresh the page it will get fixed.

Still looking like this.

image

On reload it goes away, but not happy with it. Looks like this is a fastn bug tho.

**Pull request merged**
